use std::env;

use regex::Regex;

use crate::model::{Evidence, Finding};

pub fn print(finding: &Finding) {
    println!("# why: {}", sanitize(&finding.subject));
    println!();
    println!("{}", sanitize(&finding.summary));
    println!();

    if !finding.facts.is_empty() {
        println!("| Field | Value | Evidence |");
        println!("| --- | --- | --- |");

        for fact in &finding.facts {
            let value = sanitize(&fact.value)
                .replace('|', "\\|")
                .replace('\n', "<br>");
            let evidence = match fact.evidence {
                Evidence::Confirmed => "confirmed",
                Evidence::Inferred => "inferred",
            };

            println!("| {} | {} | {} |", sanitize(&fact.label), value, evidence);
        }
        println!();
    }

    if !finding.notes.is_empty() {
        println!("Notes:");
        for note in &finding.notes {
            println!("- {}", sanitize(note));
        }
        println!();
    }

    println!(
        "_Generated by why {}. Home paths and credential-like values are redacted._",
        env!("CARGO_PKG_VERSION")
    );
}

fn sanitize(value: &str) -> String {
    let mut output = value.to_owned();

    if let Some(home) = env::var_os("HOME").and_then(|value| value.into_string().ok()) {
        output = output.replace(&home, "~");
    }

    let assignment = Regex::new(
        r"(?i)([A-Z0-9_]*(?:TOKEN|SECRET|PASSWORD|PASSWD|API_KEY|PRIVATE_KEY|CREDENTIAL|COOKIE|AUTH)[A-Z0-9_]*)=([^\s]+)",
    )
    .expect("valid credential regex");
    output = assignment
        .replace_all(&output, "$1=[redacted]")
        .into_owned();

    let option = Regex::new(
        r"(?i)((?:--?)(?:token|secret|password|passwd|api-key|private-key|credential|cookie|auth)(?:=|\s+))[^\s]+",
    )
    .expect("valid option regex");
    output = option.replace_all(&output, "$1[redacted]").into_owned();

    let url_auth =
        Regex::new(r"(?i)(https?://)[^/\s:@]+:[^@\s/]+@").expect("valid URL credential regex");
    output = url_auth.replace_all(&output, "$1[redacted]@").into_owned();

    output
}

#[cfg(test)]
mod tests {
    use super::sanitize;

    #[test]
    fn redacts_assignments() {
        assert_eq!(
            sanitize("GITHUB_TOKEN=abc123 command"),
            "GITHUB_TOKEN=[redacted] command"
        );
    }

    #[test]
    fn redacts_cli_secrets() {
        assert_eq!(sanitize("tool --token abc123"), "tool --token [redacted]");
    }

    #[test]
    fn redacts_url_credentials() {
        assert_eq!(
            sanitize("https://user:pass@example.com"),
            "https://[redacted]@example.com"
        );
    }
}
